name: 'Deployment'

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - name: Setup Pakman
        uses: upmaru/pakman@feature/chroot-alpine
        with:
          alpine: v3.18

      - name: Bootstrap Configuration
        run: |
          pakman bootstrap
        shell: alpine.sh {0}
        env:
          ABUILD_PRIVATE_KEY: ${{secrets.ABUILD_PRIVATE_KEY}}
          ABUILD_PUBLIC_KEY: ${{secrets.ABUILD_PUBLIC_KEY}}

      - name: 'Build Package'
        run: |
          cd "$GITHUB_WORKSPACE"/.apk/"$GITHUB_REPOSITORY" || exit

          abuild snapshot
          abuild -r
        shell: alpine.sh {0}

      - name: Push
        run: pakman push
        shell: alpine.sh {0}
        env:
          WORKFLOW_REF: ${{ github.ref }}
          WORKFLOW_SHA: ${{ github.sha }}
          INSTELLAR_ENDPOINT: https://sandbox.opsmaru.dev
          INSTELLAR_PACKAGE_TOKEN: ${{secrets.INSTELLAR_PACKAGE_TOKEN}}
          INSTELLAR_AUTH_TOKEN: ${{secrets.INSTELLAR_AUTH_TOKEN}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.arch }}-packages
          path: /home/runner/packages


  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with: 
          path: /home/runner/packages

      - name: Setup Pakman
        uses: upmaru/pakman@feature/chroot-alpine
        with:
          alpine: v3.18

      - name: Archive Package
        run: sudo zip -r packages.zip "$HOME"/packages
        shell: alpine.sh {0}

      # - name: 'Create Deployment'
      #   run: pakman deploy --archive packages.zip
      #   shell: alpine.sh {0}
      #   env:
      #     WORKFLOW_REF: ${{ github.ref }}
      #     WORKFLOW_SHA: ${{ github.sha }}
      #     INSTELLAR_ENDPOINT: https://sandbox.opsmaru.dev
      #     INSTELLAR_PACKAGE_TOKEN: ${{secrets.INSTELLAR_PACKAGE_TOKEN}}
      #     INSTELLAR_AUTH_TOKEN: ${{secrets.INSTELLAR_AUTH_TOKEN}}
